### ISSUE TITLE
[Organisation] Imagination des batteries à acheter / modulateurs

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#10]
## Option 1 - Réemploi des batteries NIMH d'Open Path View
L'idée est d'utiliser des packs de batteries NIMH 6 cellules.
Arnaud R doit voir pour utiliser un BEC 5V 2A, si besoin on peut récupérer celui d'Open Path View également (dans la tête photo).

### État des stock de batteries d'OPV

On dispose de 8 accus NIMH, @Benvii voit pour les recharger et mesurer la chute de tension après quelques jours voici l'état d'avancement :
| Numéro / identifiant de l'accu | Charge effectuée le | Tension après la charge  | Tension à J+6| État batteries |
|-------------------------------------- |--------------------------- |-------------------------------- |--------------------- |--------------------- |
| OPV P1 A | 13/03 à 17h  | 8.1V | 7.61V | ✅ |
| OPV P1 B | 13/03 à 23h  | 8.9V | 8.15V | ✅ |
| OPV P2 A | 13/03 à 17h  | 8.1V |7.4V | ✅ |
| OPV P2 B | 13/03 à 21h  | 8.2V | 7.87V | ✅ |
| OPV P4 A | 13/03 à 21h | 7.87V | 6.83V | ❌ |
| OPV P4 B | 13/03 à 21h  | 7,8V | 6.3V | ❌ |
| OPV P5 A | 13/03 à 21h  | 8.28V | 8.04V | ✅ |
| OPV P5 B | 13/03 à 21h  | 8.5V | 6.7V | ❌ |

## Option 2 - PowerBank + NIMH (de OPV)

Configuration de batteries : 
- PowerBank sur RPI
- 1 grand batterie nimh de OPV 7.2V 4 200 mah (lourdes et encombrante)
- chargeur OPV

Nécessite une adaptation des connectiques. On a des sérieux doute sur la longévité des batteries de OPV.

## Option 3 - PowerBank + petit niMH (iso au voiture vendu)

Configuration de batteries : 
- PowerBank pour RPI
- 1 petite batteries niMH du même format que celle des voitures c'est à dire de 2/3A en 6 cellules à 1 500 mah
- chargeurs ceux des petits voitures mais besoin d'en acheter l'autres

Référence en ligne pour les achats : 
- HibbyKing [7.2V 1500 mah nimh 2/3 A à 15,95€](https://hobbyking.com/fr_fr/turnigy-receiver-pack-2-3a-1500mah-7-2v-nimh-high-power-series.html)

## Option 4 - PowerBank + Li-ion

Configuration de batteries : 
- PowerBank pour RPI
- 1 pack de Li-Ion 7.2V 2 500 mah (voir 2 600mah) pour les moteurs : suite aux suggestions de Stéphane Blanc, ce pack serait composé de 2 `piles Li-ion format ~  ⌀ 19 x 71 mm (longeurs) - 3.7v` ce qui passage de le logement actuel avec 2 cales.
- chargeur : soit achat de nouveaux chargeur, soit réemploi des chargeur OPV étant en 1A il faudra charger 2 bloc (de 2 piles li-ion 3.7V) en même temps. Possibilité également d'utiliser les petits chargeurs fournis avec les voitures.

Référence en ligne pour les achats : 
- Chez Électro Dépôt on trouve du [2000 mah à 4€](https://www.electrodepot.fr/batterie-de-secours-edenwood-2000-mah-grise.html), ce qui reviendrait à **8€ le pack 7.2 - 2 000mah**
- Chez Pearl : on trouve des li-ion [18650 3.7 V / 2 600mah à 6,95€](https://www.pearl.fr/article/ZX1776/batterie-lithium-ion-18650-3-7-v-2600-mah), ce qui reviendrait à **13,90€ le pack de 7.2V 2 600 mah**

Simulation de la conso sur une journée (draft nécessite les retours des tests) : 
[RepartitionVoitureConso.ods](https://github.com/mdl29/donkeycarLPH/files/8456632/RepartitionVoitureConso.ods)

**Comment by Benvii** [comment]
Montage finalisé par Arnaud, testé ce soir, pour rappel on a donc alim de la PI et Moteur sur une NiMH 7.2V (j'ai testé avec la OPV 5 B, 7.2V) chargé juste avant, observations :
- 1 probable faux contact lorsque le PC bouge, reboot de la Pi
- après ~10min de pilotage la voiture est très "moule", la mesure sur la NiMH donne 6,6V, c'est trop faible

Refaire le test avec une batterie pas KO.

**Comment by Benvii** [comment]
Test d'énergie à faire cette après midi (09/04) :
- Option 1 : KO à RPI consomme trop, test fait par Benjamin déjà
- Option 2 : à tester, faire tourner la voiture au max jusqu'à perte de pêche ou arrêt moteurs, l'autonomie théoriques serait de 50min
- Option 3 : à tester avec les batteries nimh fournies avec les voitrues 1 100 / 1 200 mah, autonomie théorique de < 20 min
- Option 4 : à tester avec la batterie li-ion de Stéphane (2 600 mah), autonomie théoriques ~25min

Faire un tableau.

**Comment by Benvii** [comment]
Nous sommes parti sur l'option 4 finalement qui a fait ses preuves, autonomie de 1h30 par pack.

Maj du fichier faite il est sur le cloud LPH, reste à passer commande peut-être pour 2-3 chargeurs USB (+ câble USB vers micro USB).

**Comment by yannis-mlgrn** [comment]
Issue fixed ?

**Comment by Benvii** [comment]
Fixed we have everything.
