### ISSUE TITLE
Discover Donkeycar manager host using zero conf

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#102]
We don't know what will the computer hosting donkeycar manager API and it's hostname or IP address. We might use zeroconf to discover it.

**Comment by viandoxdev** [comment]
From a quick read of ubuntu's zeroconf page, this should be done using a service (i.e. the donkeycar manager host declares itself as being one) and just pick the first host that shows this capability with avahi-discover ?

**Comment by Benvii** [comment]
I needed it today and made quick test using python zeroconf it pretty easy see 2 demo scripts here : 
- https://github.com/mdl29/donkeycarLPH/pull/117/commits/25d313fb16975b9bf501eb46600ba192e4a5bc98

I will add it to the backend and to my PR.
