### ISSUE TITLE
Tester Intel Movidius Neural Compute

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#11]
Jean Marie nous a passé un stick USB (TPU) NCS2. Voir pour entrainer un modèle d'exemple, potentiellement via OpenVino avec et documenter les ressources trouvée.

Ensuite il faudra creuser pour voir si on peut faire tourner un entrainement de modèle DonkeyCar dessus.

**Comment by viandoxdev** [comment]
Closing as the intel NCS2 doesn't actually train, it's just used to interpret models but we don't have any use for that right  now.
