### ISSUE TITLE
Battery life test

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#110]
We need to log CPU load  (each 30 sec) :
https://www.howtogeek.com/devops/how-to-monitor-cpu-usage-in-linux-over-time/

Then try to generate a load X% : https://superuser.com/a/668332

**Comment by MaximeLM29** [comment]
```bash
top -bn1 | grep "Cpu(s)" |            sed "s/.*, *\([0-9.]*\)%* id.*/\1/" |            awk '{print 100 - $1"%"}'
```

**Comment by yannis-mlgrn** [comment]
Should be have it on dashboard donkeycar in donkeycar front. I think is useful to monitoring cpu cars...

**Comment by yannis-mlgrn** [comment]
much like that : ```top -bn1 | grep "Cpu(s)" |            sed "s/.*, *\([0-9.]*\)%* id.*/\1/" |   awk '{print "cpu :",  $1"%"}' ```

**Comment by yannis-mlgrn** [comment]
something like that but I can't get the percentage 
```awk 
top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk 'BEGIN { print "[",strftime("%m/%d/%Y %H:%M:%S", systime()),"]","cpu :",$0,"%"}'
```
Output : `[ 06/20/2022 00:08:53 ] cpu :  %`

**Comment by yannis-mlgrn** [comment]
I should use `cron`  for log these information's and in which file i put these logs. A idea @Benvii  ?

**Comment by Benvii** [comment]
Tests were done we have a battery life of ~ 3h for 10 Ah batteries.

A good way to handle it would be to have a "countdown" and at each car restart ask if the battery was change then display battery life on the management.. we did anticipate it and I'm not sure we will have the time to develop it

**Comment by yannis-mlgrn** [comment]
so close it  ?

**Comment by yannis-mlgrn** [comment]
@Benvii ?

**Comment by Benvii** [comment]
No we will simply keep the idea and do it for a next version

**Comment by Benvii** [comment]
New battery made
