### ISSUE TITLE
[Backup] Script pour trouver le meilleur bs (ibs / obs)

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#13]
Basé sur cet article : http://blog.tdg5.com/tuning-dd-block-size/

- [ ]  Voir pour écrire un script qui devrai écrire un petit fichier sur la carte, l'utiliser pour calculer les vitesse de transfert depuis la SD vers le PC avec différentes block size et mettre en avant la meilleure.
- [ ] Écrire un second script pour la restoration d'un backup qui va calculer le meilleur bs également.

Adapter le documentation du backup.

**Comment by Benvii** [comment]
Après de nombreux tests sur une carte SD, inspirés des scripts du site je vois que les valeurs changent régulièrement, c'est tout bonnement incompréhensible.

Pour aller plus loin voici d'autres approches : https://www.baeldung.com/linux/dd-optimal-blocksize

Je pense qu'il faut jouer sur les block size des 2 FS, donc ibs et obs pour trouver la bonne combinaisons et très certainement étudier la taille des caches/buffer également.

**Comment by yannis-mlgrn** [comment]
Now we use clean images with packer. We will still need this script to make a backup?

**Comment by viandoxdev** [comment]
Considering that a full dd takes about 5 min I don't think this is really necessary anymore, although faster speeds would certainly be appreciated.
