### ISSUE TITLE
[Backend] CORS

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#140]
idk why but i often have cors problems on front end: `Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://localhost:8000/cars/?skip=0&limit=4. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 500.`

**Comment by Benvii** [comment]
Test with front it's working now.
