### ISSUE TITLE
[Discord] Pas oublier le message

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#15]

**Comment by ritorizo** [comment]
quel message ?

**Comment by yannis-mlgrn** [comment]
pour demander comment faire pour importer la map ou la modéliser

**Comment by yannis-mlgrn** [comment]
response : 
`@Brian Pulfer and I have created a virtual scene with the Standard Track. You can find it here: https://github.com/BrianPulfer/sdsandbox/commits/crossroad 
G`
