### ISSUE TITLE
[ Harware ] Acheter cable HDMI

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#164]
Nous devons acheter un cable HDMI plus long pour pouvoir connecter la télé et nos pc situé sur les table|s.
> Notre cable actuel est trop petit

**Comment by yannis-mlgrn** [comment]
Nous avons un cable d'une longueure convenable, n'est ce pas @Benvii  ?

**Comment by Benvii** [comment]
Yes it's ok
