### ISSUE TITLE
[Hardware] anti-theft security for the ps4 controllers

### ISSUE THREAD

**Issue by viandoxdev** [mdl29/donkeycarLPH#18]
Because otherwise people would probably just leave with the damn thing.
We will probably just modify [this](https://www.thingiverse.com/thing:4284443), remove the phone holding part, and replace it with a hook of some sort to attach a chain or a string that will link the controller to a fence or something to prevent people from just leaving with it.

**Comment by viandoxdev** [comment]
@yannis-mlgrn you could first print the unaltered version (might have to look into the size of it) to make sure it can at least grip the controller and then we'll see into modifying the model.

**Comment by viandoxdev** [comment]
ah merde on est en francais ici

**Comment by yannis-mlgrn** [comment]
voici mon antivol pour manette de PS4 : 
- [lien thinguiverse](https://www.thingiverse.com/thing:5342314)
