### ISSUE TITLE
[ FrontEnd ] Display loading when we transfer data after record

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#183]
I want to displaying a loading bar when we have finished transfer data

**Comment by viandoxdev** [comment]
this could be done through:
 - a new text embed thing (similar to the controller icons) that shows a loading indicator. Could also add a bar with percentage, something like `"screen_msg": "[Loading(65)]"` or `Loading(<completion date timestamp>)` (for things we know the length of, i.e model computing)
 - or a new LOADING state for jobs, that the ui would pick up (a bit of a pain  for not much)

**Comment by yannis-mlgrn** [comment]
a sort of loading who just move when we train it or dl the model

**Comment by yannis-mlgrn** [comment]
no needed
