### ISSUE TITLE
[Front] extend job duration 

### ISSUE THREAD

**Issue by viandoxdev** [mdl29/donkeycarLPH#184]
Add a way to extend a job's duration in the dashboard, for people whose car broke on their turn (after the timer has been started). This would be much faster (and less annoying) than having to create a new job and put it in first.

**Comment by yannis-mlgrn** [comment]
it's impossible for @Benvii , the good way according to his is the same that our answer

**Comment by yannis-mlgrn** [comment]
I can create a button for replace the pause button who it always disable. I would create a button named reload who create the same job, put it in the first place and cancel the one who don't work.
ok, @viandoxdev  ?

**Comment by Benvii** [comment]
Job as to be created with the same worker assigned and before the previous job is ended (so that we don't have any other job assigned to this same worker that would executed before the job we want).
