### ISSUE TITLE
[Car4] Construire la voiture 4

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#19]
On a pris une 4ème voiture, basé sur un chassie différent et aussi à notre mauvaise surprise des composants différents, ce qu'il reste à faire pour qu'il puisse tourner :

- [x] Remplacement du composant ICS+ESC (+BEC) cad récepteur RF + variateur par un variateur où on pourra piloter le moteur en PWM, j'ai commandé un `QuicRun 1625 Brushed ESC 25A` chez rc-race-shop.de
- [x] Conception / adaptation de la pièce de support pour la RPi la fixation ne peux pas être la même et impression des pièces
- [x] Équiper d'une Pi4 + PiCam
- [x] Souder les différents cables (bloquer en attente du composant)

**Comment by yannis-mlgrn** [comment]
⚠️ The right steering arm is broken
- ref : 6260 steering arms 
zdhobby

**Comment by yannis-mlgrn** [comment]
🪛 ~ Réparation de la voiture N°4 
- pièce recollée ( c'est résistant ) 
Prévoir qu'elle puisse cassée dans le futur

**Comment by yannis-mlgrn** [comment]
We can close
