### ISSUE TITLE
[Matériel] Liste éléments Fête de la Science

### ISSUE THREAD

**Issue by Minemew2** [mdl29/donkeycarLPH#209]
- [x] Panneau LPH
- [x] FIche explicative manette pour user
- [ ] Fiche explicative pour l'inscription sur pc
- [ ] Etiquette pour les pcs
- [ ] Pieds de support terre-plein central
- [x] Paniers pour les manettes

**Comment by yannis-mlgrn** [comment]
no nedded, event done
