### ISSUE TITLE
[Front] Waiting time estimation, add notion of additionnal job time

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#224]
Job time estimation is only based on the drive_time parameters, some jobs like the recording job and AI_ASSISTED job perform more tasks than just drive (files transfer, training of the model ...) this include additional job running time that aren't taken into the computed time.

Those timing are most of the time known in advance (or an estimation is known) for each job type of job we could set in the estimation time algorithm those additional timings : 

- RECORD : compression and transfer time estimated to 30sec, also add 2min of model training (included during record)
- AI_ASSISTED : downloading model and uncompressed estimated to 30sec

This should be configurable and would improve time estimation if #223 is done we would have a great, precise estimation.

**Comment by viandoxdev** [comment]
Should we aim to have this for FDS ? I could hack a simple if condition in the frontend to take this into account, although it wouldn't be configurable
