### ISSUE TITLE
📢 Rent a micro and sound system

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#250]
On event due to the large space we have 50m2 it's difficult to be heard by everyone, we would benefit from a good lapel microphone and sound system.
Something like this : https://www.technimusic.fr/art-moovy-12-mk2-power-acoustics-78240.htm

We need to : 

- [x]  Contact MUN service of Brest, try to see if they have it in stock
- [ ] Otherwise contact Audiolite for instance ...

**Comment by Benvii** [comment]
Mail sent to Florence (MUN - VB), waiting for a reply.

**Comment by yannis-mlgrn** [comment]
done !

**Comment by Benvii** [comment]
Yes received and it works, still need to be added in a check list, done here for now : #266
