### ISSUE TITLE
Built around 12 new battery pack (load balanced)

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#251]
We are changing all our battery management system and we will be using lithium-ion batteries with some additive wiring to be able to load balance the charge.

We need to adapt the connectors on all cars : 

- [x] MonkeyCar
- [x] DababyCar
- [x] BlueCar
- [x] The new one (?), we need to name it

Build 12 batteries : 

- Number of battries made : 0 / 12

_Also assigned to : Steph & Arnaud_

**Comment by yannis-mlgrn** [comment]
done !

**Comment by Benvii** [comment]
Everything is done and fully charged
