### ISSUE TITLE
UX : Visual way to explain how training works

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#261]
We just have 1 sentences explaining that the training is in progress, in fact we would really need more than that. We though of several little animation that would explain it while the training is in progress (or waiting for an AI runner).

Illustrations here : https://photos.app.goo.gl/xQVnCwuDEJDePayx8 

We will have several stages : 

1. Explain that the collected data set is split into 2 portions (during max 40 sec)
2. Show the AI as a student in a class room learning the notion of turning right and left with a teacher (during 30-40 sec)
3. Explain how the model is evaluated (it's precision, recall and so on), with the AI being tested on some images that we keep out of it's training

First illustration made by @Nils-Abjorn are available here (we should make a PR) : 

1. ![Step 1 - Data Split](https://user-images.githubusercontent.com/1092728/235461825-9ed7e378-0c1c-4e3a-8f4d-1ce1ed561ef1.svg)
2. ![Step 2 - Learning](https://user-images.githubusercontent.com/1092728/235461824-157533c8-fde8-4195-800b-9db457b1e511.svg)
3. ![Step 3 - Evaluation](https://user-images.githubusercontent.com/1092728/235461976-22bac37f-e492-4ca5-b525-827181dd4417.svg)

**Comment by Nils-Abjorn** [comment]
![0](https://user-images.githubusercontent.com/74726881/236633236-b91f8290-70cc-4765-9b46-4b04121566bf.svg)

**Comment by Nils-Abjorn** [comment]
![0](https://user-images.githubusercontent.com/74726881/236637379-c4acfb4e-918b-4946-a2a2-1cb763cc6214.svg)
