### ISSUE TITLE
AI Worker : script installation have 2 VM ready

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#263]
We are stuck because of multiple parallele trainings that need to be done, the task / job model let's us do that but we need one more trainer (VM for that) to be able to process more jobs in parallel also we need a clean way to recover in case the trainer VM breaks.

We should script the installation of donkeycar using Ansible for a paperspace basic ubuntu VM (P4000).

**Comment by yannis-mlgrn** [comment]
link to #159

**Comment by Benvii** [comment]
Manually installed on a second virtual machine
