### ISSUE TITLE
Event Arkéa Bordeaux - Attestations droit à l'image

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#269]
Solliciter les parents pour les attestations de droit à l'image CMA de Yannis et Titouan en profiter pour leur transmettre un planning du déplacement.

**Comment by yannis-mlgrn** [comment]
- [ ] Yannis
- [ ] Titouan

**Comment by Benvii** [comment]
Dans le doc barrer : 17 mars, écrire 15mai. Barrer Paris / Vincennes, écrire Bordeaux.

**Comment by Benvii** [comment]
Ok For titouan also
