### ISSUE TITLE
[Ansible] Role "raspi-config", basic raspberry pi configurations

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#27]
**Needs #26 to be merged before.**

Create a base role, this role will be used for generic raspberry pi configuration stuff not directly related to DonkeyCar projet.

This role should : 

- [x] Enable SSH, by creating /boot/ssh file, using Ansible [file module with state: touch](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html)
- [x] Configure wifi, based on a template file that will be copied to `/etc/wpa_supplicant/wpa_supplicant.conf`. Parameters (country code, wifi ssid and psk) should use variables defined in group_vars/all
- [x] Perform update and upgrade using the [Ansible apt module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#ansible-collections-ansible-builtin-apt-module) see in the exemple task `Run the equivalent of "apt-get update" as a separate step`, for upgrade use `upgrade: safe` option see exemples in documentation
- [x] Change password for pi user, with password defined as variable, you might take a [look at this article](https://jianjye.medium.com/how-to-update-user-password-with-ansible-f971f41a3b3e) or simply use command `chpasswd` (see [how raspi-config does the job](https://github.com/raspberrypi-ui/rc_gui/blob/master/src/rc_gui.c#L132))
- [x] Enable I2C [look at here](https://github.com/raspberrypi-ui/rc_gui/blob/master/src/rc_gui.c#L81)
- [x] Enable camera

Take care to use named tasks and templates.

That's all :)

**Comment by yannis-mlgrn** [comment]
`%d` == 1

**Comment by Benvii** [comment]
You also need to install pigpio :
```bash
sudo apt update && sudo apt install pigpio python3-pigpio
sudo systemctl start pigpiod
```
