### ISSUE TITLE
[Ansible] Role "donkeycar"

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#28]
**Needs #26 to be merged before.**

Create a new role "donkeycar", will represent a basic donkeycar installation (without optionnal stuff such as OpenCV..). You will find all informations in donkeycar documentation website : https://docs.donkeycar.com/guide/robot_sbc/setup_raspberry_pi/ 

This role should :

- [x] Step 8: Install Dependencies, using Ansible APT module, you can install multiple modules with : https://stackoverflow.com/a/63668940
- [x] Step 10: Setup Virtual Env, take a look at how we have [created virtualenv in Open Path View](https://github.com/OpenPathView/OPV_Ansible/blob/master/roles/base/tasks/opv.yml#L28), don't forget to add source line to bashrc using [lineinfile module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html). If you don't use the linInFile module line might be added multiple times if we re-excute the book
- [x] Step 11: Install Donkeycar Python Code, clone repository (using [git module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html)), use [file module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html) to create directories and [pip module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) for pip commands

Take care you need to become *pi* user for all task in this role.

Good luck :)

**Comment by yannis-mlgrn** [comment]
It necessary to put the step 10 into the middle of the step 11

**Comment by yannis-mlgrn** [comment]
pip install -e : https://stackoverflow.com/questions/24449134/how-to-run-python-setup-py-develop-command-inside-virtualenv-using-ansible
