### ISSUE TITLE
[Ansible] Role ps4-controller

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#33]
Create a role to install ds4drv service to handle only 1 controller at a time by car.

This role should :
- [x] Install ds4drv using Ansible git module from : https://github.com/Benvii/ds4drv/tree/193_limit_simultaneous_controllers  and their service file
- [x] Their own LED color, will be put in a configuration file based on the ethernet MAC address, read it from a file of find a wait to deploy it in ds4drv configuration at the right time, we might need to create a service to deploy "car specific" configuration

**Comment by Minemew2** [comment]
To create ds4drv service, first create a folder named donkeycar in /etc/. In this folder, create a txt file named controller_color.txt. In this file, write the choosen color for your controller, in hexadecimal format (ie : af9666).

**Comment by Minemew2** [comment]
To handle devices with ds4drv, it is necessary to do the following command lines :
sudo wget https://raw.githubusercontent.com/chrippa/ds4drv/master/udev/50-ds4drv.rules -O /etc/udev/rules.d/50-ds4drv.rules
sudo udevadm control --reload-rules
sudo udevadm trigger

**Comment by Minemew2** [comment]
Then, clone the following git repository in /home/pi : https://github.com/Benvii/ds4drv.git

**Comment by Minemew2** [comment]
You also need to checkout to this branch : 193_limit_simultaneous_controllers

**Comment by Minemew2** [comment]
In the repo file, install  ds4drv python files : $ python setup.py install

**Comment by Minemew2** [comment]
Now create the service. In /etc/systemd/system/, create a txt file name ds4drv.service. Put the following code in this file : 
[Unit]
Description=ds4drv daemon
Requires=bluetooth.service
After=bluetooth.service

[Service]
EnvironmentFile=/etc/donkeycar/ds4drv.env
ExecStart=sudo /home/pi/env/bin/ds4drv --controller-limit 1 --led ${controller_color}
Restart=on-abort

[Install]
WantedBy=bluetooth.target
