### ISSUE TITLE
[Software] Gerer les manettes bluetooth sur les voitures

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#5]
Permettre aux voitures de pouvoir se connecter à une manette bluetooth

**Comment by Minemew2** [comment]
Manette 1 : 1C:A0:B8:6D:1C:BA

**Comment by Minemew2** [comment]
Manette 1 : 1C:A0:B8:6D:1C:BA

**Comment by Minemew2** [comment]
Manette 2 : 1C:A0:B8:35:3D:F0

**Comment by Minemew2** [comment]
Rappel : on utilise ds4drv pour controler les manettes

**Comment by Minemew2** [comment]
Pour avoir les logs des manettes :
mettre :
/home/pi/env/bin/ds4drv --led e52ce0 --daemon --daemon-log /var/log/ds4drv.log
dans /etc/rc.local
(à la place de l'ancienne commande)

**Comment by Minemew2** [comment]
Pour voir les argument que reçoit la commande à l'appel, on ira print la variable options, ligne 197 dans le config.py
