### ISSUE TITLE
[Ansible] Shortcut to take full resolution picture (check camera quality)

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#55]
En tant qu'animateur je souhaites pouvoir vérifier que le capteur photo est OK (focus, saletés ...).

On pourra simplement effectuer une prise de photo via un bouton de la manette à un emplacement fixe (exemple /tmp/testPhoto.jpg ) et fournir une documentation sur comment récupérer l'image (scp).

Attention pour faire un raspistill il faut stopper le service donkeycar qui utilise la caméra, prendre la photo, relancer le service. C'est pas un problème de le stopper comme un fera cette vérification en cas de doute donc quand la voiture tourne pas (probablement au démarrage).
Penser a faire une doc sur comment récupérer l'image via scp, on ne cherchera pas à faire mieux pour l'instant.

**Comment by Benvii** [comment]
@yannis-mlgrn you want to take this ticket ?

**Comment by yannis-mlgrn** [comment]
Of courses
