### ISSUE TITLE
[hardware] Don't loose any camera cap (rpi cam 2 wide angle)

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#57]
As a donkeycar user I will find it pretty useless to have a sort of camera cap support on the 3D printed parts.

It would simply be a cone of the size of the camera cap so that we can put the cap on it when it's not on the camera.

* DonkeyCar parts source : https://a360.co/2STUhf5
* Thingiverse : https://www.thingiverse.com/thing:2566276

Todo :

- [x] Add a cone of the cap size : diameter 14 mm, height 7mm (no more needed)
- [x] Print it on a small piece, to test it
- [x] Then add it to donkeycar base part
- [x] Printed for bluecar (blue)
- [x] Printed for monkecar (white --> green)
- [x] Printed for dababycar (purple)
- [x] Printed for pimpcar (red --> magenta)
- [x] Publish the thing and send it to DonkeyCar Discord

**Comment by yannis-mlgrn** [comment]
where is the better position for allow the user to put and re

**Comment by Benvii** [comment]
We need 2 STL separate files so that we can easily print them, can you generate 2 separate files ? Thanks

**Comment by Benvii** [comment]
@yannis-mlgrn can you split them into 2 separate STL so that I can print them and replace the parts ?

**Comment by yannis-mlgrn** [comment]
Already done

**Comment by Benvii** [comment]
Thanks it's here : https://github.com/mdl29/donkeycarLPH/blob/main/3dDesigns/camera-cover/lowPart.stl

**Comment by Benvii** [comment]
Missing some screw to fix the raspberry pi, order was made they should arrive by the end of next week.

**Comment by Benvii** [comment]
I'm closing it, not sure we will push it to donkeycar community
