### ISSUE TITLE
Traduce some docs in english 

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#67]
We should traduce the doc in English for allow to every persons to understand and use our project

**Comment by viandoxdev** [comment]
translate* to* for* everyone*

**Comment by viandoxdev** [comment]
And sure I can do this

**Comment by yannis-mlgrn** [comment]
> We should ~traduce~ **translate** the doc in English ~for~ **to** allow ~for every persons~ **everyone** to understand and use our project

Outch , while i understand me is good

**Comment by yannis-mlgrn** [comment]
> And I can do this if you want
if you want, of course

**Comment by yannis-mlgrn** [comment]
useless
