### ISSUE TITLE
[Organisation] Faire l'organisation des courses

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#7]

**Comment by Benvii** [comment]
🛒 Commandes faites aujourd'hui, je me suis saigné de près de 300 balles 💸 :
- 1 autre voiture RC, commandée sur Bangood, un modèle un peu différent mais elle était qu'a 50 balles
- 2 Pi 4 (8Go .. car reste que ça sur toute le marché 😭), pour équiper la 3ème et 4ème caisse
- 3 Pi Cam 8 Mpx, grand angle (160 deg)

Manque les cartes micro SD à prendre chez électo dépôt.
