### ISSUE TITLE
Test and adjust configurations for all cars

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#75]
Following #60 

We need to test the latest main image on all cars, check they are correctly running (limit the speed also), using [this latest image](https://donkeycar-lph-packer-builds.s3.eu-west-3.amazonaws.com/1/main.img.tar.gz) :
- [ ] Bluecar
- [ ] Dababycar
- [ ] Monkeycar
- [ ] Pimpcar

Test procedure : 
1. Boot car
2. Pair PS4 controller and check it's color
3. Drive with the car

**Comment by yannis-mlgrn** [comment]
Fixed
