### ISSUE TITLE
[Software] Faire la backup de la carte SD

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#8]
Faire un backup de la carte SD de dababycar, voir pour le stocker quelques part.

Doc à lire concernant les tailles de bloc : http://blog.tdg5.com/tuning-dd-block-size/

**Comment by Benvii** [comment]
Le backup est fait il est sur mon poste `/home/benjamin/Documents/MDL/LPH/DonkeyCarSDBackup/2022-03-05_dababycar-debutSeanceLPH.img`, fingerprint sha256 `COMPUTE IN PROGRESS`

**Comment by Benvii** [comment]
Je réouvre ce ticket car il nous faut une procédure de backup scripté ou documentée.

J'ai commencé à faire des tests avec [PiShrink](https://github.com/Drewsif/PiShrink), pour l'instant je peux confirmer que le mode (sans le cleaning des log & co, option `-p` marche).

Todo : 
- [ ] Documenter une procédure de sauvegarde (éventuellement scriptée), qui réduit l'image et la compresse
- [ ] Héberger les backup dans le cloud (bucket S3 AWS par exemple)
