### ISSUE TITLE
Broken camera connector - bluecar

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#98]
Bluecar as suffered a lot and it's camera connector is partially broken on on side, the camera still works, the PCB is also broken on the same side so it fits well. But we might experience some disconnection of the connector, we need to stick this connector to ensure we want experience any issue.

**Comment by yannis-mlgrn** [comment]
we have to change the connector 
## tasks : 
- [ ] change connector
- [ ]  test new camera

**Comment by Benvii** [comment]
Fixed and tested
